# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55138a05a8e8338b71bb0056c5d8624e1a196473ab9c3e235d00700b6ddbb023204e444997e3998e362d41d850e2089f1f1c3f8c64acb6934ba3d5ab2b4b7922

test:
  secret_key_base: 54bd3cc0035b13be36a09b9359ddecd3a43baf2ac9f1e72d06df1c6a0df33ac9f7eee60cddcc7f6b398e65a637a0cfbf6353b71df3565ec457195109092278b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
